apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostpath-multihost-manager
  labels:
    k8s-app: hostpath-multihost-manager
  namespace: kube-system

spec:
  selector:
    matchLabels:
      k8s-app: hostpath-multihost-manager

  template:
    metadata:
      labels:
        k8s-app: hostpath-multihost-manager

    spec:
      containers:
        - name: hostpath-multihost-manager
          image: kubeboost/hostpath-multihost-manager:latest
#          env:
#            - name: PV_DIR
#              value: /var/kubernetes
#
#            - name: PV_RECLAIM_POLICY
#              value: Retain

          volumeMounts:
            - name: pv-volume
              mountPath: /var/kubernetes

      volumes:
        - name: pv-volume
          hostPath:
            path: /var/kubernetes
