apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-multihost-provisioner
  labels:
    k8s-app: hostpath-multihost-provisioner
  namespace: kube-system

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      k8s-app: hostpath-multihost-provisioner

  template:
    metadata:
      labels:
        k8s-app: hostpath-multihost-provisioner

    spec:
      containers:
        - name: hostpath-multihost-provisioner
          image: kubeboost/hostpath-multihost-provisioner:v1.0.0
