apiVersion: v1
kind: Service
metadata:
  name: hostpath-multihost-manager
  labels:
    k8s-app: hostpath-multihost-manager
  namespace: kube-system

spec:
  clusterIP: None
  selector:
    k8s-app: hostpath-multihost-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
